### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mrapczynski** [jamischarles/atom-todo-show#27] opened 2014-12-19 14:55 UTC
Uncaught TypeError: Cannot read property 'length' of undefined

**Atom Version**: 0.162.0
**System**: Mac OS X 10.10.1
**Thrown From**: [todo-show](https://github.com/jamischarles/atom-todo-show) package, v0.6.0

### Steps To Reproduce

1. Clicked hyperlink to file that contains the TODO item detected

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

TypeError: Cannot read property 'length' of undefined
  at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:387:29)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:939:53)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:991:27)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/display-buffer.js:643:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2627:33)
  at TextEditorView.module.exports.TextEditorView.scrollToBufferPosition (/Applications/Atom.app/Contents/Resources/app/src/text-editor-view.js:224:25)
  at ShowTodoView.module.exports.ShowTodoView.moveCursorTo (/Users/mrapczynski/.atom/packages/todo-show/lib/show-todo-view.coffee:266:18)
  at /Users/mrapczynski/.atom/packages/todo-show/lib/show-todo-view.coffee:256:8
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:509:49
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

/cc @atom/core

**Comment by diracdeltafunk** [comment] 2015-03-23 15:44
Steps to Reproduce:

1. Create a file without having the package installed
2. Install the package
3. Without restarting Atom, add a FIXME, TODO, CHANGED, or XXX message in the file
4. Open the Todo-show Results tab
5. Click the link to attempt to navigate to the newly created file

The order of these steps is important. I could not replicate the error with files I created after the package was installed, or with files I had created prior to package installation after an atom restart.

**Atom Version**: 0.187.0
**System**: linux 3.16.0-31-generic
**Thrown From**: [todo-show](https://github.com/jamischarles/atom-todo-show) package, v0.8.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /usr/share/atom/resources/app/node_modules/q/q.js:128

TypeError: Cannot read property 'length' of undefined
  at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:391:29)
  at TextBuffer.module.exports.TextBuffer.clipPosition (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:943:53)
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/usr/share/atom/resources/app/src/display-buffer.js:1007:27)
  at DisplayBuffer.module.exports.DisplayBuffer.scrollToBufferPosition (/usr/share/atom/resources/app/src/display-buffer.js:659:47)
  at TextEditor.module.exports.TextEditor.scrollToBufferPosition (/usr/share/atom/resources/app/src/text-editor.js:2725:33)
  at TextEditorView.module.exports.TextEditorView.scrollToBufferPosition (/usr/share/atom/resources/app/src/text-editor-view.js:222:25)
  at ShowTodoView.module.exports.ShowTodoView.moveCursorTo (/home/REMOVED/.atom/packages/todo-show/lib/show-todo-view.coffee:271:18)
  at /home/REMOVED/.atom/packages/todo-show/lib/show-todo-view.coffee:261:8
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:756:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:516:49
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:366:11)

```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": REMOVED
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
haskell-pointfree, v0.1.0
ide-haskell, v0.3.6
language-haskell, v1.0.0
todo-show, v0.8.0

# Dev
No dev packages
```

**Comment by bagong** [comment] 2015-05-04 17:52
Can confirm exactly as reported: error is thrown if you run the function before restarting Atom, it's gone after restarting.

**Comment by MRodalgaard** [comment] 2015-05-07 20:07
This does indeed still exists for `atom --one`

**Comment by MRodalgaard** [comment] 2015-05-07 22:37
0.9.0 of todo-show is out. Would you please test if you can reproduce this issue?

**Comment by ligoore** [comment] 2015-05-25 19:16
+1

**Comment by MRodalgaard** [comment] 2015-05-25 19:20
@ligoore; +1 meaning you still see the problem with Atom 0.201.0 and todo-show 0.10.0?

**Comment by ligoore** [comment] 2015-05-25 19:32
Unfortunately, yes. It happened just after I wrote "TODO" to my .cpp file and refreshed the list. It was when I wanted to jump to my "TODO" from the list that this error occured. Also it produced lots of Atom issues.

**Comment by MRodalgaard** [comment] 2015-05-25 19:38
Okay, well that needs to be fixed. And it only happened just after you installed the package, as @diracdeltafunk described.

**Comment by MRodalgaard** [comment] 2015-05-30 08:35
At last I was able to consistently reproduce this issue.

It turned out to be a result of the match range not being serialized when the package was installed midway and the match had not been saved yet (still in textEditor buffer).

It was horible to reproduce and debug this problem, since it was only present at new installs. If someone wants to confirm that the fix works and receive a free hug from me:
 1. Uninstall todo-show package and quit atom
 2. Open atom again and create a new file
 3. Install todo-show package
 4. Write `TODO: this is a todo` in new file without saving the changes
 5. Apply patch to `.atom/packages/todo-show` and save (without closing or saving the other editor window)
 6. Run todo-show
 7. Click the newly created but not yet saved TODO
 8. Jump to line without a crash

Else it will be included in the next release.

Thank you @mrapczynski for reporting this, thank you @diracdeltafunk for posting the reproduction steps and thank you @ligoore for the extra info.

**Closed by MRodalgaard** 2015-05-30 08:35 UTC
